clickhouse_output add ck dynamic schema acquisition function,change t…
childe/gohangout pull request #158
Opened 2022-01-26 03:23 UTC by kingwide

…he ck ddl only need to reboot gohangout

2022-01-26 15:25 UTC, childe requested changes

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +					keyIntValue := event[keyInt]
感觉这里需要使用 `if v, ok := event[keyInt];ok {}

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +var transIntColumn = make(map[string]string)
应该是 []string 类型吧。 map 类型没用上。

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +			c.defaultValue[columnName] = nil
Nullable 就要把默认值设置成 nil 吗？ 这个我到是也不确定。

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +	// }
注释的代码可以直接删了吧？

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +	if len(p.fields) <= 0 {
我没有找到哪里设置了 p.fields 。 这里不会始终 == 0 吗？

2022-01-26 15:25 UTC, childe commented on output/clickhouse_output.go
> +				continue
一定要有 message 字段？ 感觉不应该这样。

2022-01-27 01:30 UTC, kingwide commented on output/clickhouse_output.go
> +			c.defaultValue[columnName] = nil
这个我认为是有必要的，使用这个类型的原因是int型的默认值是0，但是某些字段为0在业务上也许有业务含义，故默认值不能为0

2022-01-27 02:48 UTC, kingwide commented on output/clickhouse_output.go
> +var transIntColumn = make(map[string]string)
后面有用到map的key是字段名，v是字段类型
```
for key1, value1 := range c.desc {
			switch value1.Type {
			case "Int64", "UInt64", "Int32", "UInt32", "Int16", "UInt16", "Int8", "UInt8", "Nullable(Int64)", "Nullable(Int32)", "Nullable(Int16)", "Nullable(Int8)":
```suggestion
var transIntColumn = make(map[string]string)
```
				transIntColumn[key1] = value1.Type
			case "Array(String)", "Array(Int64)", "Array(Int32)", "Array(Int16)", "Array(Int8)":
				transArrayColumn[key1] = value1.Type
			case "Float64", "Float32":
				transFloatColumn[key1] = value1.Type
			}
			c.fields = append(c.fields, key1)
		}
		transIntColumnSize = len(transIntColumn)
		transArrayColumnSize = len(transArrayColumn)
		transFloatColumnSize = len(transFloatColumn)
		return
```

2022-01-27 02:53 UTC, kingwide commented on output/clickhouse_output.go
> +	if len(p.fields) <= 0 {
在setTableDesc()方法中赋值的，此方法中变量名是c
```
for key1, value1 := range c.desc {
			switch value1.Type {
			case "Int64", "UInt64", "Int32", "UInt32", "Int16", "UInt16", "Int8", "UInt8", "Nullable(Int64)", "Nullable(Int32)", "Nullable(Int16)", "Nullable(Int8)":
				transIntColumn[key1] = value1.Type
			case "Array(String)", "Array(Int64)", "Array(Int32)", "Array(Int16)", "Array(Int8)":
				transArrayColumn[key1] = value1.Type
			case "Float64", "Float32":
				transFloatColumn[key1] = value1.Type
			}
			c.fields = append(c.fields, key1)
		}
```

2022-01-27 02:54 UTC, kingwide commented on output/clickhouse_output.go
> +				continue
这里写的有问题我把这块删掉

2022-01-27 02:59 UTC, childe commented on output/clickhouse_output.go
> +var transIntColumn = make(map[string]string)
`v是字段类型` ，但字段类型没有用到吧

2022-01-27 03:24 UTC, kingwide commented on output/clickhouse_output.go
> +var transIntColumn = make(map[string]string)
数组处理这块有用到v 要根据columnArrayType 判断
```
if transArrayColumnSize > 0 {
				for keyArray, columnArrayType := range transArrayColumn {
					keyArrayValue := event[keyArray]
					if keyArrayValue == nil {
						continue
					}
					switch columnArrayType {
					case "Array(Int64)", "Array(Int32)", "Array(Int16)", "Array(Int8)":
						arrayIntValue := keyArrayValue.([]interface{})
						arrayIntLen := len(arrayIntValue)
						ints := make([]int, arrayIntLen)
						for i := 0; i < arrayIntLen; i++ {
							arrayIntConverterValue, err := c.intConverter(arrayIntValue[i])
							if err == nil {
								ints[i] = arrayIntConverterValue.(int)
							} else {
								glog.V(10).Infof("ch_output convert arrayIntType error: %s", err)
								ints[i] = 0
							}
						}
						event[keyArray] = ints
					}
				}
			}
```

2022-01-27 06:29 UTC, kingwide commented on output/clickhouse_output.go
> +					keyIntValue := event[keyInt]
会在下次提交优化此部分的逻辑判断

2022-01-27 08:21 UTC, merged